<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParkingVision.Data\ParkingVision.Data.csproj" />
  </ItemGroup>
</Project>
