<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParkingVision.Data\ParkingVision.Data.csproj" />
  </ItemGroup>
</Project>
